spring.application.name=demob1
server.port=8081

# LAB 5 - Bài 4: CSDL J6Students cho StudentRestApi
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=J6Students;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=123
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
