spring.application.name=demo
# Lab 4 - Quan ly sinh vien chay tai cong 8081
server.port=8081

# Dia chi project Quan ly diem (cong 8082)
score-service.base-url=http://localhost:8082

# H2 in-memory database
spring.datasource.url=jdbc:h2:mem:studentdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
