spring.application.name=demo
# Lab 3.2 project chay dong thoi tai cong 8002
server.port=8002

# Dia chi project Lab 3.1 (cong 8001) de goi sang lay users
lab31.base-url=http://localhost:8001

# H2 in-memory database
spring.datasource.url=jdbc:h2:mem:lab32db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
